package JavaScript.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = 'naming_convention_unique_for_project' (id = 'JavaScript_02IE')
from your code and delete the patch script.
*/
deleteBuildType("naming_convention_unique_for_project")

